<?php

namespace Naissance\ApplicationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceRepository extends EntityRepository
{
	public function getReferencesByWishlist($wishlist)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r', 'p')
            ->join('r.product', 'p')
            ->where('r.wishlist = :wishlist')
            ->setParameter('wishlist', $wishlist);

        return $qb->getQuery()->getResult();
    }
}
