<?php

namespace Naissance\ApplicationBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Naissance\UserBundle\Entity\User;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends EntityRepository
{

    public function getWishlistByWishlistIdAndUser($wishlistId, User $user)
    {
        $qb = $this->createQueryBuilder('w')
        ->select('w')
        ->where('w.id = :wishlist_id')
        ->andWhere('w.user = :user')
        ->setParameter('wishlist_id', $wishlistId)
        ->setParameter('user', $user);

        return $qb->getQuery()->getSingleResult();
    }

    // public function getUserWishlists($userId) {
    //     return $this->findBy(
    //         array('user_id' => $userId), 
    //         array('id' => 'desc') // Tri
    //     );
    // }

}
