<?php

namespace Naissance\ApplicationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends EntityRepository
{
}
